name: Generate File List

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-file-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file list
        run: |
          mkdir -p data
          find data -type f | sed 's|^data/||' | jq -R . | jq -s . > data/files.json

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/files.json
          git diff --cached --quiet || (git commit -m "Update file list" && git push)
